### ISSUE TITLE
MapIt Global: stale OSM data - needs fresh import

### ISSUE THREAD

**Issue by schlos** [mysociety/global.mapit.mysociety.org#18]
I'm opening this ticket based on mysociety/mapit#104. I don't see any files being committed in the repo for the import, so I assume import is done by script/code on the Global server.

At the moment last OSM import was done on 10th January 2018 (based on [generations data](https://global.mapit.mysociety.org/generations.html)).

Latest administrative borders on MapIt Global in use for Croatia (8 and 9 generations) do not have most of the wards, cities and counties/municipalities available, so we cannot rely on MapIt for some projects such as FixMyStreet.

Specifically, for Croatia, OSM community was very busy in the past 2-3 years and now we have all Croatian ward, city and county borders available on OpenStreetMap.

It it possible to do Global update? Or if that is not possible at least Croatian administrative borders. If necessary I can provide more details.

Much appreciated!

**Comment by dracos** [comment]
Am downloading new planet now, will see how it goes, as you say, hasn't been run for a while.

**Comment by dracos** [comment]
The import of new areas up to the planet export (so mid January sometime) has finished successfully; it is now updating the country listings based on point-in-polygon checks. Hopefully this now has the data you require in it, I can see new Croatian boundaries in there e.g. https://global.mapit.mysociety.org/area/1352906.html

**Comment by schlos** [comment]
Thanks @dracos ! I can see previously missing municipalities.

Is update on Global MapIt still in progress? Should I wait little more for update process to be completed?

**Comment by dracos** [comment]
No, it has finished.

**Comment by schlos** [comment]
Looks great, thanks!
I will close this ticket if you agree.

**Comment by dracos** [comment]
Glad to hear it :)
